### ISSUE TITLE
Taco Crash

### ISSUE THREAD

**Issue by KoraxaExe** [KreloX/CornDelight#4]
Apparently the client crashes when you consume a taco from Corn Delight, all other foods from the same mod don't do that.
People stated that you disconnect when you consume it on a server, and crash if you consume it in singleplayer

error given (on crash) is

The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1935.method_8389()" because "$$0" is null

Mod version is 1.0.3 and 1.0.4

**Comment by KreloX** [comment]
Thanks for the report. Can you please specify what version of minecraft you are experiencing this issue on? Also specify the used modloader (fabric or quilt) and it's version.

**Comment by KoraxaExe** [comment]
Sure!
Minecraft 1.20.1
Fabric 0.14.22

**Comment by KreloX** [comment]
I can't reproduce this issue, so it's probably a conflict with another mod. Try removing the other mods one by one to figure out which one causes this conflict.

**Comment by KoraxaExe** [comment]
The modpack had 125 mods, I removed them one by one so it took me a while, sorry for that 
I ended up removing Farmer's Delight (which is needed for Corn Delight to work), and when I added it back, Curseforge automatically installed an updated version of Farmer's Delight, at that point it started working.

(The version I had installed was 1.4.1, the updated version is 1.4.3)
It works perfectly now
