### ISSUE TITLE
Add support for Farmer's Delight Refabricated

### ISSUE THREAD

**Issue by Flatkat** [KreloX/CornDelight#6]
Farmers Delight Fabric (https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric) has been deprecated in favor of a new Fabric/Quilt Farmer's Delight mod: https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated
Some tweaks may be needed for proper compatibility.

**Comment by KreloX** [comment]
Thanks for the suggestion. This was already planned and I will probably work on it the following month.
