### ISSUE TITLE
Crash on Server side because of version mismatch

### ISSUE THREAD

**Issue by Dumpling00** [KreloX/CornDelight#8]
<img width="462" alt="image" src="https://github.com/user-attachments/assets/af26af21-e7c9-4fc1-aaf1-4a96890cfe5b">

Hello! Was wondering if it isn't too much trouble, if this could be fixed in any way?
We aren't in the best condition of updating our loader nor the base mod - we are playing on a modpack we can best describe as a jenga tower.

Thank you for your time and consideration.

**Comment by KreloX** [comment]
Fixed this in 1.1.2
